spring:
  application:
    name: daviweb
  profiles:
    default: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/daviweb_db}
    username: ${DB_USERNAME:daviweb_user}
    password: ${DB_PASSWORD:daviweb_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080